# Generated by Django 5.1.7 on 2026-09-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_genotype', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genotype',
            options={'ordering': ['coordinate__pos', 'sample', 'id']},
        ),
        migrations.AddField(
            model_name='chromosome',
            name='first_pos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chromosome',
            name='last_pos',
            field=models.IntegerField(null=True),
        ),
    ]
